### ISSUE TITLE
docs(graphql*compodoc*github): add documentaion [WiP]

### ISSUE THREAD

**Issue by VladiRR** [VladiRR/svvs#14]
#### проговорить
- [x] ссылки что посмотреть 
- [x] работа с гитхаб
- [x] настройка IDE под себя
[вебинар от разработчиков](https://www.youtube.com/watch?v=Ozt8pBq9Mys&list=WL&index=3&t=1s) 
- [x] в очередной раз поправить скрипты (backend => db)

## На данном этапе необходимо выполнить следующее:
- [x] добавить комментарии к файлам graphql 
- [x] добавить генерацию документации для приложений
[настройка compodoc | Nx документация](https://nx.dev/latest/angular/guides/running-custom-commands#steps)
- [x] решить проблему нескольких приложений и README.md в корне репозитория
- [x] настроить скрипты
- [x] добавить документацию на github page
- [x] настроить экшен для автогенерации документации

```
name: Generate documentation
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Copy branch [master]
        uses: actions/checkout@v2
      - 
        name: Install NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - 
        name: Install dependencies
        run: npm install      
      - 
        name: Run compodoc
        run: npx nx affected --all --target=compodoc    
      - 
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GH_PAGE }}
```
