### ISSUE TITLE
feat(db): add PostgreSQL db [WiP]

### ISSUE THREAD

**Issue by VladiRR** [VladiRR/svvs#5]
## На данном этапе необходимо выполнить следующее:
- [x] установить зависимости
`yarn add @nestjs/typeorm typeorm pg`

- [x] импортировать модуль typeorm в app.module

- [x] настроить файл .env
```
PORT=3000
DB_TYPE=postgres
DB_NAME=SVVS_DB
DB_HOST=localhost
DB_HOST_NAME=postgres
DB_PORT=5433
DB_USER_NAME=postgres
DB_USER_PASSWORD=123456
PGADMIN_PORT=5555
PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
PGADMIN_DEFAULT_PASSWORD=admin
FRONTEND_CLIENT_PORT=4201
```

- [x] создать базу данных

### докер 
```
version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    hostname: ${DB_HOST_NAME}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
```

### скрипты
```
    "db:start": "cp .env ./docker-compose && cd docker-compose && docker-compose up -d",
    "db:stop": "cd docker-compose && docker-compose stop && rm .env",

```

- [x] подключить БД

### настройки подключения
```
export const environment = {
  production: false,
  connection: {
    type: process.env.DB_TYPE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USER_NAME,
    password: process.env.DB_USER_PASSWORD,
    database: process.env.DB_NAME,
    dropSchema: false,
    synchronize: true,
    logging: true,
    entities: [
      'dist/apps/backend/api/src/**/*.entity{.ts, .js}'
    ],
    migrations: [
      'dist/apps/backend/api/migrations/*{.ts, .js}'
    ],
    cli: {
      'migrationsDir': 'db/migrations'
    }
  }
};

```
